name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Upgrade pip and install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies with pipenv
        run: |
          pipenv install --dev --deploy || pipenv install --dev

      - name: Install Playwright browsers
        run: pipenv run python -m playwright install --with-deps

      - name: Lint with ruff
        run: pipenv run ruff check .

      - name: Run pytest
        run: pipenv run pytest
